services:
  - type: web
    name: telegram-bot-admin
    env: python
    plan: free
    buildCommand: ""
    startCommand: "sh -c 'python main.py & gunicorn app:app --bind 0.0.0.0:8000'"
    envVars:
      - key: PORT
        value: 8000